use_frameworks!

target 'AFPopUpMenu_Example' do
  pod 'AFPopUpMenu', :path => '../'

  target 'AFPopUpMenu_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
